### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by zaporylie** [FreshMail/REST-API#2]
Gdzieś powinna się znaleźć informacja o wersji API by móc zadbać o kontrolę zgodności biblioteki.

**Comment by piotr-cz** [comment]
Na przykład w pliku [composer.json](https://github.com/FreshMail/REST-API/blob/master/composer.json) oraz w sekcji [releases](https://github.com/FreshMail/REST-API/releases).

Przydała by się również rejestracja biblioteki w [packagist.org](http://packagist.org)

**Comment by grzesiekgorczyca** [comment]
Rzadko zmieniamy coś w naszej bibliotece, ale czasami się zdarza. Dzisiaj dodałem zmiany zaproponowane przez społeczność oraz kilka naszych. Dodałem także wersjonowanie, kolejne poprawki będą miały ustawiane tagi także będą widoczne w zakładce releases.
